In [3]:
import numpy as np

In [4]:
arr = np.arange(0,11)
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10]


In [5]:
arr[5]

5

In [6]:
arr[0:6]

array([0, 1, 2, 3, 4, 5])

In [7]:
arr[2:9]


array([2, 3, 4, 5, 6, 7, 8])

In [8]:
arr[0:3]=999

In [9]:
arr

array([999, 999, 999,   3,   4,   5,   6,   7,   8,   9,  10])

In [13]:
arr_copy = arr.copy()

In [14]:
arr_copy[3:9]=1001

In [15]:
arr_copy

array([ 999,  999,  999, 1001, 1001, 1001, 1001, 1001, 1001,    9,   10])

In [17]:
arr_2d =np.array( [[5,10,15],[20,25,30],[35,40,45]])
arr_2d[2,1]

40

In [18]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [26]:
arr_2d[2:,:3]

array([[35, 40, 45]])

In [27]:
arr_3 = np.arange(25,50)

In [28]:
arr_3

array([25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41,
       42, 43, 44, 45, 46, 47, 48, 49])

In [30]:
arr_3[arr_3<=39]

array([25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39])