In [8]:
import  numpy as np
arr = np.arange(0,11)
arr


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [9]:
arr+arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [10]:
arr*3

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30])

In [16]:
arr = (arr ** 2)%2
arr

array([0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0], dtype=int32)

In [22]:
arr = np.arange(0,11)
arr = np.sqrt(arr)
arr


array([ 0.        ,  1.        ,  1.41421356,  1.73205081,  2.        ,
        2.23606798,  2.44948974,  2.64575131,  2.82842712,  3.        ,
        3.16227766])

In [23]:
np.max(arr)

3.1622776601683795

In [24]:
np.min(arr)

0.0

In [28]:
arr = np.arange(20,40)
np.sin(arr)

array([ 0.91294525,  0.83665564, -0.00885131, -0.8462204 , -0.90557836,
       -0.13235175,  0.76255845,  0.95637593,  0.27090579, -0.66363388,
       -0.98803162, -0.40403765,  0.55142668,  0.99991186,  0.52908269,
       -0.42818267, -0.99177885, -0.64353813,  0.29636858,  0.96379539])